#version: '3.8'

services:
  # Service MySQL
  mysql__db:
    image: l80000000/mysql_home
    container_name: mysql__db
    restart: always
    environment:
      MYSQL_DATABASE: transport_db
      MYSQL_PASSWORD: Lawliet2004
      MYSQL_ROOT_PASSWORD: Lawliet2004
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - transport_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 5s

  # Service Laravel (Backend)
  laravel__app:
    image: l80000000/projet-linux-laravel_app:latest
    container_name: laravel__app
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      mysql__db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql__db
      DB_PORT: 3306
      DB_DATABASE: transport_db
      DB_USERNAME: root
      DB_PASSWORD: Lawliet2004
    ports:
      - "8000:8000"
    networks:
      - transport_network

  # Service PhpMyAdmin
  phpmyadmin:
    image: l80000000/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql__db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql__db
    networks:
      - transport_network

# Volumes persistants
volumes:
  mysql_data:

# RÃ©seaux
networks:
  transport_network:
    driver: bridge
